### ISSUE TITLE
The gift card redeem page seems not to be working

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#102]
WP: 6.0.0
WC: 6.5.1 
Description:
The gift Card redeem page seems not to be working. Gift Card details are not showing
![image](https://user-images.githubusercontent.com/85384857/173034938-652e79b3-db2f-4ef8-88dd-ead5668bfbf4.png)
And when pro plugin is activated the coupon shows invalid 
![image](https://user-images.githubusercontent.com/85384857/173275787-e045835a-3e46-4d5f-8402-dfff3cad1f9e.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
No issue

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
