### ISSUE TITLE
Make the notice for a minimum price limit issue more descriptive 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#104]
WordPress version: 6.0.0
WooCommerce version: 6.6.1
Version: 2.4.3
Description:
Make the notice for a minimum price limit issue more descriptive 
![image](https://user-images.githubusercontent.com/85384857/176850217-154ea770-6e9d-4b3c-96a5-474a95bbcea2.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
