### ISSUE TITLE
The text color and font size is different:

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#106]
WordPress version: 6.0.0
WooCommerce version: 6.6.1
Version: 2.4.3
Description:
The text color and font size is different:
![image](https://user-images.githubusercontent.com/85384857/176882608-d4e98ccc-3002-4d6e-a7a7-0a170ddb8cf3.png)

We can change the font colour on the dropdown:
![image](https://user-images.githubusercontent.com/85384857/177143015-b313f460-713e-4172-a331-66159a2e7210.png)

Either put colon to every heading or remove from every heading:
![image](https://user-images.githubusercontent.com/85384857/177143237-4f19757b-ac3f-4de9-9851-c1db930110e2.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
