### ISSUE TITLE
PHPcs issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#111]
File:
[PHPcs-ORG.zip](https://github.com/wpswings/woo-gift-cards-lite/files/9506761/PHPcs-ORG.zip)
[woo-gift-cards-lite.zip](https://github.com/wpswings/woo-gift-cards-lite/files/9506762/woo-gift-cards-lite.zip)

**Comment by Puneet-cedcoss** [comment]
2 phpcs issues left which are related to the file name change .  we can't change the file name it will create the issue.

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
