### ISSUE TITLE
Desinging issue on Onboarding form

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#115]
Word Press: 6.1.0
WooComerce: 7.1.0
Description: 
The Onboarding form is out of design. The heading needs space after the input box.
![image](https://user-images.githubusercontent.com/85384857/199227772-be1bb773-b784-4180-a2be-307a07525b55.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
