### ISSUE TITLE
Incorrect delivery method is showing in the Gift card preview

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#116]
Word Press: 6.1.0
WooComerce: 7.1.0
Description:
Incorrect delivery method is showing in the Gift card preview when added as a shortcode on the template
![image](https://user-images.githubusercontent.com/85384857/199233556-d9c5f1b6-85c7-4f9f-a6e7-f7d365be3248.png)
![image](https://user-images.githubusercontent.com/85384857/199245547-0f7def7f-5f56-45e2-b950-de5a8e161b78.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
