### ISSUE TITLE
PHP malware issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#117]
ObfuscatedPhp /home/cedcoss/Desktop/woo-gift-cards-lite/includes/class-woocommerce-gift-cards-common-function.php
0x65c:$concat_with_spaces: $recommand_product .= '<style>.ugcfw__product_table_img img {width: 125px;height: 125px;}.ugcfw__product_table_name h2 {text-align:center; padding: 0;margin: 0;font-size: 24px;line-height: 28px;text-transform: capitalize;}</style><table class="ugcfw__product_table"><tr class="ugcfw__product_table_row"><td class="ugcfw__product_table_img" style="vertical-align: top;padding-bottom:15px;width:125px;">' . $recommand_prod->get_image() . '</td><td class="ugcfw__product_table_name" style="padding: 0 0 15px 25px;wi
0x7f1:$concat_with_spaces: $recommand_prod->get_image() . '</td><td class="ugcfw__product_table_name" style="padding: 0 0 15px 25px;width: 450px;text-align: center;"><h2 style="text-align:center;padding: 0;margin: 0;font-size: 24px!important;line-height: 28px;text-transform: capitalize;">' . $recommand_prod->get_name() . '</h2><p class="ugcfw__product_table_price" style="padding: 10px 0;margin: 0;font-size: 20px;line-height: 28px;font-weight: bold;">' . get_woocommerce_currency_symbol() . $recommand_prod->get_price() . '</p><p class

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
