### ISSUE TITLE
Change the Happy Mothers Day to Happy Mother's Day in the template

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#118]
Word Press: 6.1.0
WooComerce: 7.1.0
Description:
Change the **Happy Mothers Day** to **Happy Mother's Day** in the template. So that uploaded by new user correct spelling should show.
![image](https://user-images.githubusercontent.com/85384857/199258158-37700ad7-86db-456f-9c22-ea4aa182f357.png)

**Comment by Puneet-cedcoss** [comment]
template is editable and it is coming from the server

**Comment by Puneet-cedcoss** [comment]
anyone can change the template name there is no issue

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
