### ISSUE TITLE
The expiry date should change according to the date mentioned on the "select date"

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#119]
Word Press: 6.1.0
WooComerce: 7.1.0
Description:
The expiry date should change according to the date mentioned on the "select date" 
![image](https://user-images.githubusercontent.com/85384857/200227472-b36fc956-b55d-4eb5-966b-6c7203872217.png)
![image](https://user-images.githubusercontent.com/85384857/200228998-a4d28477-e6e5-4b87-a492-ac21f5bbb410.png)

If we change the select date, the date on "Gift Card Preview" should change automatically so that the user gets an idea of the expiry date.
![image](https://user-images.githubusercontent.com/85384857/200227445-d12cb7a1-69d8-46a6-bf80-e2e367746b0e.png)

**Comment by Puneet-cedcoss** [comment]
expiry date is depend on the gift card purchase date 
![Screenshot from 2022-11-07 12-41-37](https://user-images.githubusercontent.com/79438024/200247105-fb3fea6b-5809-410b-a0f3-d5cda647957e.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
