### ISSUE TITLE
Both tooltip have the same description

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#120]
Word Press: 6.1.0
WooComerce: 7.1.0
Description:
Both tooltips have the same description, which may confuse the users
![image](https://user-images.githubusercontent.com/85384857/200544056-e52afda5-b24d-426b-84ce-2de2c137636e.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
