### ISSUE TITLE
PHPcs issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#121]
File:
[PHPcs-1.zip](https://github.com/wpswings/woo-gift-cards-lite/files/9960717/PHPcs-1.zip)
[woo-gift-cards-lite.zip](https://github.com/wpswings/woo-gift-cards-lite/files/9960718/woo-gift-cards-lite.zip)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
