### ISSUE TITLE
Warning Showing 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#128]
Woo Commerce Version - 7.2.2
WordPress Version - 6.1.1
Plugin Version - 2.4.9
Description -
Warning Showing 
![image](https://user-images.githubusercontent.com/85384857/211516752-6e2ac5a0-2b42-4a53-909e-adffeda9d1f1.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
![image](https://user-images.githubusercontent.com/85384857/212357886-0ddf439a-0d04-4a19-a716-55739defd69e.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
