### ISSUE TITLE
The in Thank you page and Mail to the sender and receiver  and in order page have not been translated

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#129]
Woo Commerce Version - 7.2.2
WordPress Version - 6.1.1
Plugin Version - 2.4.9
Description -
The Thank you page and Mail to the sender and receiver  and in order page have not been translated
![image](https://user-images.githubusercontent.com/85384857/211519676-b0b424e5-9d55-4a3a-be2f-636524221c96.png)
![image](https://user-images.githubusercontent.com/85384857/211519855-0a9b03e5-ea91-4309-925b-ba44c4e5bbd1.png)
![image](https://user-images.githubusercontent.com/85384857/211519904-f3dc86bb-b21d-4289-b2a3-0072d75ccd0e.png)
![image](https://user-images.githubusercontent.com/85384857/211521053-d6d20e20-4165-4a16-a46d-8a1c67b544db.png)
![image](https://user-images.githubusercontent.com/85384857/211526495-a0908043-31e1-494a-a100-4116d5f8b3bc.png)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
These codes are translatable when the PRO plugin is activated
