### ISSUE TITLE
PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#130]
[PHPcs.zip](https://github.com/wpswings/woo-gift-cards-lite/files/10385079/PHPcs.zip)
[woo-gift-cards-lite.zip](https://github.com/wpswings/woo-gift-cards-lite/files/10385080/woo-gift-cards-lite.zip)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
