### ISSUE TITLE
When we are translating the Email template, the template names are not visible

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#136]
Woo Commerce Version - 7.5.0
WordPress Version - 6.1.1
Plugin Version - 2.5.1
Description -
When we are translating the Email template, the template names are not visible
![image](https://user-images.githubusercontent.com/85384857/225827437-6fb9ef3a-29f6-4ff8-89ea-98321ddfc6b3.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
