### ISSUE TITLE
update authorization button should display after activating the pro plugin only

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#138]
Woo Commerce Version - 7.5.1
WordPress Version - 6.2
Plugin Version - 2.5.2
Description -
update authorization button should display after activating the pro plugin only
![image](https://user-images.githubusercontent.com/85384857/231677642-f3adfece-c828-47d1-b994-bbaa9126e50e.png)

**Comment by Puneet-cedcoss** [comment]
![Screenshot from 2023-05-23 14-31-45](https://github.com/wpswings/woo-gift-cards-lite/assets/79438024/1c9d6339-e7e3-47cf-967e-582d93a4b48f)

**Comment by Sukirti-CEDCOSS** [comment]
verified
