### ISSUE TITLE
Change colour to blue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#140]
Word Press: 6.2.1
WooCommerce: 7.7.0
Plugin version: 3.6.3
Description:
Change color to blue
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/1a94670b-08ec-4d1a-845c-bf75fe0698d4)
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/9b2d8eef-dc7a-4bf0-8154-8ee26f715065)

**Comment by Puneet-cedcoss** [comment]
fixed
