### ISSUE TITLE
One of the options should be pre-selected 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#142]
Status - New
Woo Commerce Version - 7.8.0
WordPress Version - 6.2.2
Plugin Version - 2.5.6
Description:
One of the options should be pre-selected 
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/d96ac9c1-b22d-474b-9674-2fdcb5806a25)

**Comment by Puneet-cedcoss** [comment]
already working

**Comment by Puneet-cedcoss** [comment]
![Screenshot from 2023-06-27 12-59-22](https://github.com/wpswings/woo-gift-cards-lite/assets/79438024/730b4b55-e9d1-42b6-945b-1e529c495b36)

**Comment by Sukirti-CEDCOSS** [comment]
verified
