### ISSUE TITLE
Change GiftCards to Gift Cards

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#148]
Status - New
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 3.6.0
Description:
Change GiftCards to Gift Cards
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/1cb6f5dc-1ba7-4bd1-aafa-bdd18995a50b)

**Comment by Puneet-cedcoss** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
Verified
