### ISSUE TITLE
Change to WPS on every Templates

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#149]
Status - New
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 3.6.0
Description:
Change to WPS on every Template
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/9a7a04e7-c9d7-40ac-90f8-59892a85d3f4)

**Comment by Puneet-cedcoss** [comment]
it's just coupon code it will anything
