### ISSUE TITLE
PHPcs Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#150]
Status - New
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 3.6.0
Description:
[PHPcs.xml.zip](https://github.com/wpswings/woo-gift-cards-lite/files/12726707/PHPcs.xml.zip)
[woo-gift-cards-lite.zip](https://github.com/wpswings/woo-gift-cards-lite/files/12726708/woo-gift-cards-lite.zip)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Still there are some issue:
[PHPcs.xml.zip](https://github.com/wpswings/woo-gift-cards-lite/files/12748667/PHPcs.xml.zip)
[woo-gift-cards-lite.zip](https://github.com/wpswings/woo-gift-cards-lite/files/12748668/woo-gift-cards-lite.zip)

**Comment by Sukirti-CEDCOSS** [comment]
Fixed
