### ISSUE TITLE
Theme Compatibility Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#151]
Status - New
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 3.6.0
Description:
Theme Compatibility Issue
Theme: Astra
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/4f90e210-df4c-4644-9879-fdc28b634cb8)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
