### ISSUE TITLE
If ORG is updated by the user that already has PRO then 2 pages of Balance is creating 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#152]
Status - New
Woo Commerce Version - 8.1.1
WordPress Version - 6.3.1
Plugin Version - 3.6.0
Description:
If ORG is updated by the user that already has PRO then 2 pages of Balance are creating 
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/4c566171-4e87-4cc4-ba35-b91d3d65e5e3)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
