### ISSUE TITLE
Provide a pop-up with a button for the user to direct to the pro purchase site

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#154]
Status - New
Woo Commerce Version - 8.2.1
WordPress Version - 6.2.1
Plugin Version - 2.6.1
Description -
Provide a pop-up with a button for the user to direct to the pro purchase site

https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/53f40a2a-dd6e-4147-874f-3590a16cb146

**Comment by Puneet-cedcoss** [comment]
provided

**Comment by Sukirti-CEDCOSS** [comment]
Verified
