### ISSUE TITLE
Change this button name to "Import New Templates"

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#155]
Status - New
Woo Commerce Version - 8.2.1
WordPress Version - 6.2.1
Plugin Version - 2.6.1
Description -
Change this button name to "Import New Templates"
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/b543c224-605f-4c14-ae69-126757c5c8c0)

**Comment by Puneet-cedcoss** [comment]
string changed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
