### ISSUE TITLE
Replace it with a proper icon of the Gift Card

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#156]
Status - New
Woo Commerce Version - 8.2.1
WordPress Version - 6.2.1
Plugin Version - 2.6.1
Description -
Replace it with a proper icon of the Gift Card
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/7daf4199-b441-4dd0-9967-6734bae8706a)

**Comment by Puneet-cedcoss** [comment]
this enhancement is not included in this version of chanelog so i schedule it for next update

**Comment by pradeepsinghbisht-cedcoss** [comment]
it is theme related nothing to do with our plugin

**Comment by pranjali-wps** [comment]
issue fixed
