### ISSUE TITLE
The template pop is too small for the preview

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#157]
Status - New
Woo Commerce Version - 8.2.1
WordPress Version - 6.2.1
Plugin Version - 2.6.1
Description -
The template pop is too small for the preview
![image](https://github.com/wpswings/woo-gift-cards-lite/assets/85384857/c17f82c5-121b-41e4-af7b-abf4fd3fb211)

**Comment by Puneet-cedcoss** [comment]
![Screenshot from 2023-10-20 09-48-30](https://github.com/wpswings/woo-gift-cards-lite/assets/79438024/dc375595-3f66-433b-8069-efb7fb9584ab)

**Comment by Puneet-cedcoss** [comment]
please check template preview in standard screen resolution

**Comment by Sukirti-CEDCOSS** [comment]
Verified
