### ISSUE TITLE
Incorrect Spelling.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#159]
WP Version - 6.3.2
WP Version - 8.2.1
Plugin version - 2.6.2
Description -  Incorrect Spelling.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/d130ffe5-7ff8-47f7-a10f-615fd2e332a0)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
