### ISSUE TITLE
The "PREVIEW" button is not working, When I click on the Preview button then it redirects to the "Page not found" page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#160]
WP Version - 6.3.2
WP Version - 8.2.1
Plugin version - 2.6.2 (ORG and PRO)
Description - The "PREVIEW" button is not working, When I click on the Preview button then it redirects to the "Page not found" page.

[scrnli_31_10_2023_19-08-03.webm](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/65b9f5fe-e597-4c6f-b423-05a665c34bad)

**Comment by Puneet-cedcoss** [comment]
fix

**Comment by pranjali-wps** [comment]
issue fixed
