### ISSUE TITLE
The new layout should be already enabled for the new users.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#166]
WP Version- 6.5.2
WC Version - 8.8.2
Plugin Version - 2.6.9
Description- The new layout should be already enabled for the new users.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/7895d2fe-62b0-42f9-81eb-0d0bec393da4)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
still pending issue

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/45dc3e84-3abd-4a58-a164-5c20be99c539)

**Comment by Puneet-cedcoss** [comment]
please check again

**Comment by pranjali-wps** [comment]
Still pending "The new layout should be already enabled for the new users "

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
