### ISSUE TITLE
There should be a banner for the New layout.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#167]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.6.9
Description - There should be a banner for the New layout.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/b526a605-7c32-4980-a4a0-3f344529e852)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
verified
