### ISSUE TITLE
The plugin version should be updated.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#168]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.6.9
Description - The plugin version should be updated.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/081ded0b-2f34-4cdb-8686-90fa76d2fcca)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
