### ISSUE TITLE
Plugin check issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#169]
WP Version - 6.5.2
WC Version - 8.8.2
Plugin Version - 2.6.9
Description - PLugin check issue

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/9d4d43f1-fa65-4459-8865-c310c9135c11)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
still pending issue

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/451100f6-e75a-4d37-b16b-e9286927c54d)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
