### ISSUE TITLE
Without enabling WooCommerce, Activate the ORG plugin displays a fatal error.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#170]
WP Version- 6.5.2
WC Version - 8.8.2
Plugin Version - 2.6.9
Description- Without enabling WooCommerce, Activate the ORG plugin displays a fatal error.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/a056fead-71c4-45e7-a750-ff1a808070f4)

**Comment by Puneet-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
issue fixed
