### ISSUE TITLE
Wrong setting name. It should be "Set expiry days" on the product edit page.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#172]
WP Version - 6.5.2
WC Version - 8.8.3
Plugin Version - ORG -2.8.10
Description - Wrong setting name. It should be "Set expiry days" on the product edit page.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/f733e69c-935e-40f4-9f49-25c36d3a2f14)

**Comment by Puneet-cedcoss** [comment]
string changed

**Comment by pranjali-wps** [comment]
issue fixed
