### ISSUE TITLE
Need proper Captilization for the Demo word-- DEMO

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#174]
WP Version - 6.5.3
WC Version - 8.9.0
Plugin version - ORG
Description - Need proper Captilization for the Demo word-- DEMO

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/18d9e584-335f-49ed-bcbd-2a59bd2987e4)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
