### ISSUE TITLE
There should be an email notification, Whenever I redeem the coupon and the Coupon converts into points. 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#175]
WP Version - 6.5.3
WC Version - 8.9.0
Plugin version - ORG
Description - There should be an email notification, Whenever I redeem the coupon and the Coupon converts into points. 

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/005f29c1-82bf-431c-9d00-7323367d49b3)

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/634ac3b4-a5c6-4247-8934-9810e6f5e2a9)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done - coupon amount email notification will be work here,

**Comment by pranjali-wps** [comment]
**issue fixed**

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/1352dc74-4627-456f-b108-611d765a409d)
