### ISSUE TITLE
When GC org and GC CC both plugin are activated then fatal error should not be happen

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#176]
WP Version - 6.5.3
WC Version - 8.9.0
Plugin version - ORG
Description - When GC org and GC CC plugins are activated then the fatal error should not happen

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/4e28b527-1aea-48ce-86c0-a70c046b11ac)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
**still pending issue**

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/9efa8bda-9d03-41bf-a10f-b3d83af32af8)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
fixed
