### ISSUE TITLE
The "Disable Apply Coupon Fields" feature issue

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#178]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - 3.0.1
Description - The "Disable Apply Coupon Fields" is enabled then I have added a GC product and a non-GC product, The User can apply a coupon the on GC product.

Suggestion - if a coupon is applied, then the coupon amount should be deducted from the non-GC product amount.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/fcd171e6-5e42-4955-a872-c4b6c56becfd)

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/b72452d7-3631-40d5-944b-326a2e9cc016)

**Comment by pradeepsinghbisht-cedcoss** [comment]
not an issue - this setting is for whether apply coupon field should be display or not.
if checked then it shouldn't display for GC product only
if unchecked then it should display for GC product only

**Comment by pranjali-wps** [comment]
discussed with the anshu sir.
