### ISSUE TITLE
 The text is not valid for the price it should be a number field.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#179]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - 3.0.1
Description - The text is not valid for the price it should be a number field.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/60a44e27-9393-47a3-aa8a-289969e5c120)

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/6a43de14-d74f-43ae-9eef-cabfa610dcc6)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
