### ISSUE TITLE
The price range should be lower to higher. price range is applied higher to lower .

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#180]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - 3.0.1
Description - The price range should be lower to higher. price range is applied higher to lower.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/d1afd7e3-4991-4bac-9c21-bb4cf970f83e)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
