### ISSUE TITLE
the User is not able to enter a decimal value.

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#181]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - 3.0.1
Description - If I have entered the decimal value in the price range value and then in the frontend, I have entered a decimal value, the User is not able to enter a decimal value.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.06.25-17_20_45.webm](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/fdaa0486-525a-473e-bc8d-60a0771096ac)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
