### ISSUE TITLE
The "USER PRICE" pricing type issue 

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#183]
WP Version - 6.5.5
WC Version - 9.0.2
Plugin Version - 3.0.1
Description - There should be a validation that the default price is not less than the set minimum price.

![image](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/96b553cb-1610-4aee-b62f-ad7fe137b136)

[scrnli_25_06_2024_18-15-46.webm](https://github.com/wpswings/woo-gift-cards-lite/assets/129398279/b66ca43f-3353-4a3d-b172-413e0fbe857f)

**Comment by pradeepsinghbisht-cedcoss** [comment]
validation is already on the frontend if someone click on add to cart button

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
