### ISSUE TITLE
PLUGIN CHECK

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#185]
WP Version - 6.6
WC Version - 9.1.2
Plugin Version - ORG
Description - PLUGIN CHECK

![image](https://github.com/user-attachments/assets/1787af3e-5d8e-4702-98d0-5b150ae643ce)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
