### ISSUE TITLE
Displayed WordPress database error on GC reports section

### ISSUE THREAD

**Issue by pranjali-wps** [wpswings/woo-gift-cards-lite#187]
WP Version - 6.6.1
WC Version - 9.2.1
Plugin version - 3.0.3
Description - 

Displayed WordPress database error on GC reports section

![image](https://github.com/user-attachments/assets/cf35816a-0a29-4575-a06d-904a1844134b)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by pranjali-wps** [comment]
**Pending issue**

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pranjali-wps** [comment]
issue fixed
