### ISSUE TITLE
Templates which can't be used in product as Gift Card Template are displaying.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [wpswings/woo-gift-cards-lite#51]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Admin panel --> Gift Cards --> Templates
Version: 2.0.10
Description: The Templates which can't be used in the product as Gift Card Template are displaying.
![Screenshot (1)](https://user-images.githubusercontent.com/76723329/114868521-a1bcbc00-9e13-11eb-8111-427275219eec.png)

**Comment by Sukirti-CEDCOSS** [comment]
Still an issue:
![image](https://user-images.githubusercontent.com/85384857/176870541-07d33479-5582-44de-b554-cc78469c8e43.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
