### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#94]
WC: 6.4.1
WP: 5.9.3
Description:
Php error is showing 
![image](https://user-images.githubusercontent.com/85384857/167543538-4778b089-415c-4578-a767-5e57388928e4.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
