### ISSUE TITLE
The price are not reflecting as option chosen

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-gift-cards-lite#95]
WC: 6.4.1
WP: 5.9.3
Description:
The price are not reflecting as option chosen
![image](https://user-images.githubusercontent.com/85384857/167544276-5452640a-f09d-4f56-8eeb-bb761f1706f6.png)
![image](https://user-images.githubusercontent.com/85384857/167544412-6ce57b78-7b1e-4df2-9ace-923da15d8f36.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by Sukirti-CEDCOSS** [comment]
verified
